version: "3"
services:

  srv-mqtt:
    container_name: srv-mqtt
    image: eclipse-mosquitto
    volumes:
      - "./svc/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    networks:
      antena:
        ipv4_address: "172.0.33.2"
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  srv-static:
    container_name: srv-static
    image: nginx:alpine
    networks:
      antena:
        ipv4_address: "172.0.33.3"
    ports:
      - "80:80"
    volumes:
      - "./static:/usr/share/nginx/html:ro"
      - "./svc/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - srv-mqtt
    restart: unless-stopped

networks:
    antena:
        driver: bridge
        ipam:
            config:
                - subnet: 172.0.33.0/24
